mqtt:
  enabled: false

go2rtc:
  streams:
    living_room:
      - rtsp://guestacc:FrigateGuest@192.168.1.13:554/stream1 # <- stream which supports video & aac audio.
      - ffmpeg:living_room#audio=aac#hardware
    bed_room:
      - rtsp://guestacc:FrigateGuest@192.168.1.14:554/stream1 # <- stream which supports video & aac audio.
      - ffmpeg:bed_room#audio=aac#hardware
    yard:
      - rtsp://guestacc:FrigateGuest@192.168.1.15:554/stream1 # <- stream which supports video & aac audio.
      - ffmpeg:yard#audio=aac#hardware

detectors:
 ov_1:
   type: openvino
   device: GPU
 ov_2:
   type: openvino
   device: GPU
 ov_3:
   type: openvino
   device: GPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt   

cameras:
  living_room: # <------ Name the camera
    enabled: true
    ffmpeg:
      apple_compatibility: true # <- Adds compatibility with MacOS and iPhone
      inputs:
        - path: rtsp://guestacc:FrigateGuest@192.168.1.13:554/stream1 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        Main Stream: living_room
    notifications:
      enabled: true
  bed_room: # <------ Name the camera
    enabled: true
    ffmpeg:
      apple_compatibility: true # <- Adds compatibility with MacOS and iPhone
      inputs:
        - path: rtsp://guestacc:FrigateGuest@192.168.1.14:554/stream1 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        Main Stream: bed_room
    notifications:
      enabled: true
  yard: # <------ Name the camera
    enabled: true
    ffmpeg:
      apple_compatibility: true # <- Adds compatibility with MacOS and iPhone
      inputs:
        - path: rtsp://guestacc:FrigateGuest@192.168.1.15:554/stream1 # <----- The stream you want to use for detection
          input_args: preset-rtsp-restream
          hwaccel_args: preset-vaapi
          roles:
            - record
            - detect
            - audio
      output_args:
        record: preset-record-generic-audio-aac
    live:
      streams:
        Main Stream: yard
    notifications:
      enabled: true
detect:
  enabled: true
version: 0.16-0
notifications:
  enabled: true
  email: hoanlk@craftzlife.com
record:
  enabled: true
  sync_recordings: true
  retain:
    days: 30
    mode: motion
  alerts:
    retain:
      days: 3
      mode: motion
  detections:
    retain:
      days: 30
      mode: motion
semantic_search:
  enabled: false
  model_size: small
face_recognition:
  enabled: false
  model_size: small
lpr:
  enabled: false
classification:
  bird:
    enabled: true
camera_groups: {}
